version: "3.9"

services:
  db:
    container_name: "ms-archiver-db"
    image: "postgres:13.5-alpine3.14"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    tty: true
  redis:
    container_name: "ms-archiver-redis"
    image: "redis:6.2.6-alpine3.14"
    tty: true
  server:
    container_name: "ms-archiver-server"
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; pnpm run typeorm:run && node dist/main'
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    ports:
      - "10002:10002"
    tty: true
